global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    static_configs:
    - targets: ["node-exporter:9100"]

  - job_name: "iowatcherng-exporter"
    static_configs:
    - targets: ["iowatcherng-exporter:9975"]